services:
  api:
    build:
      context: ../../services/api
    restart: always
    command: fastapi dev main.py --host 0.0.0.0 --port 8000
    volumes:
      - ../../services/api:/app
    ports:
      - "${API_PORT}:8000"
    environment:
      - MYSQL_HOST=${MYSQL_HOST:-db} # Optional. Default value is "db"
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PORT=${MYSQL_PORT}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
